# Generated by Django 4.2.3 on 2023-07-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.EmailField(default=2, max_length=254, verbose_name='Contact phone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='about',
            field=models.TextField(verbose_name='Product about'),
        ),
    ]
