# Generated by Django 4.2.3 on 2023-07-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_contact_phone_alter_product_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=40, verbose_name='Contact phone'),
        ),
        migrations.AlterField(
            model_name='product',
            name='about',
            field=models.TextField(verbose_name='about product'),
        ),
    ]
