# Generated by Django 4.2.3 on 2023-07-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_contact_phone_alter_product_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Category name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Category name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=60, null=True, verbose_name='Category name'),
        ),
    ]
